src/main/java/ru/evseenko/entity/Task.java
package ru.evseenko.entity;

import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import org.hibernate.annotations.CacheConcurrencyStrategy;
import org.jetbrains.annotations.Nullable;
import org.springframework.cache.annotation.Cacheable;

import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.QueryHint;
import javax.persistence.Table;


@Entity
@Setter
@Getter
@Cacheable
@NoArgsConstructor
@Table(name = "app_task")
@org.hibernate.annotations.Cache(usage = CacheConcurrencyStrategy.READ_WRITE)
@NamedQueries({
        @NamedQuery(
                name = Task.FIND_ALL,
                query = "select task from Task task where task.user.id = :userId",
                hints = { @QueryHint(name = "org.hibernate.cacheable", value = "true") }

        ),
        @NamedQuery(
                name = Task.FIND_BY_NAME,
                query = "select task from Task task where task.name like CONCAT(:name,'%') " +
                "and task.user.id = :userId",
                hints = { @QueryHint(name = "org.hibernate.cacheable", value = "true") }
        ),
        @NamedQuery(
                name = Task.FIND_BY_DESC,
                query = "select task from Task task where task.description like CONCAT(:description,'%') " +
                "and task.user.id = :userId",
                hints = { @QueryHint(name = "org.hibernate.cacheable", value = "true") }
        ),
        @NamedQuery(
                name = Task.FIND_BY_PROJECT,
                query = "select task from Task task where task.project.id = :projectId " +
                "and task.user.id = :userId",
                hints = { @QueryHint(name = "org.hibernate.cacheable", value = "true") }
        )
})
public class Task extends Domain {

    public static final String FIND_ALL = "Task.findAll";
    public static final String FIND_BY_NAME = "Task.findByNamePart";
    public static final String FIND_BY_DESC = "Task.findByDescriptionPart";
    public static final String FIND_BY_PROJECT = "Task.findTaskForProject";
    public static final String DELETE_ALL = "Task.deleteAll";

    @Nullable
    @JoinColumn(name = "project_id")
    @ManyToOne(fetch = FetchType.LAZY)
    private Project project;
}

src/main/java/ru/evseenko/controller/TaskController.java
package ru.evseenko.controller;

import com.ocpsoft.pretty.faces.annotation.URLMapping;
import com.ocpsoft.pretty.faces.annotation.URLMappings;
import org.jetbrains.annotations.NotNull;
import org.primefaces.event.RowEditEvent;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Scope;
import org.springframework.web.context.WebApplicationContext;
import ru.evseenko.api.service.IProjectService;
import ru.evseenko.api.service.ITaskService;
import ru.evseenko.entity.Status;
import ru.evseenko.entity.dto.ProjectDTO;
import ru.evseenko.entity.dto.TaskDTO;
import ru.evseenko.entity.dto.UserDTO;
import ru.evseenko.exception.ServiceException;
import ru.evseenko.util.ControllerUtil;

import javax.annotation.PostConstruct;
import javax.faces.application.FacesMessage;
import javax.faces.context.FacesContext;
import javax.inject.Named;
import java.util.Arrays;
import java.util.Date;
import java.util.List;
import java.util.UUID;

@Named("task")
@Scope(WebApplicationContext.SCOPE_REQUEST)
@URLMappings( mappings = {
        @URLMapping(id = "task",
                pattern = "/task",
                viewId = "/WEB-INF/views/task/list.xhtml"),
        @URLMapping(id = "taskAdd",
                pattern = "/task/add",
                viewId = "/WEB-INF/views/task/add.xhtml")
})
public class TaskController {

    private final ITaskService taskService;
    private final IProjectService projectService;
    private final UserDTO user;
    private final TaskDTO task;
    private List<TaskDTO> tasks;

    @Autowired
    public TaskController(ITaskService taskService, IProjectService projectService) {
        this.taskService = taskService;
        this.projectService = projectService;
        this.user = ControllerUtil.getCurrentUser();
        this.task = new TaskDTO();
    }

    @PostConstruct
    public void init() {
        tasks = taskService.getAll(user.getId());
    }

    public String addTask() {
        final String userId = user.getId();
        task.setUserId(userId);
        task.setId(UUID.randomUUID().toString());
        task.setCreateDate(new Date());
        taskService.persist(userId, task);

        @NotNull final FacesMessage msg = new FacesMessage("Task", "Task add success");
        FacesContext.getCurrentInstance().addMessage(null, msg);

        return "list.xhtml?faces-redirect=true";
    }

    public void onRowEdit(RowEditEvent event) {
        @NotNull final String userId = user.getId();
        @NotNull final Object obj = event.getObject();
        @NotNull final TaskDTO taskUpd;
        if (obj instanceof TaskDTO) {
            taskUpd = (TaskDTO) obj;
        } else {
            throw new ServiceException("invalid object");
        }

        taskService.update(userId, taskUpd);
        tasks = taskService.getAll(userId);

        @NotNull final FacesMessage msg = new FacesMessage("Task Edited", taskUpd.getName());
        FacesContext.getCurrentInstance().addMessage(null, msg);
    }

    public void onRowCancel(RowEditEvent event) {
        final FacesMessage msg = new FacesMessage("Edit Cancelled", ((TaskDTO) event.getObject()).getName());
        FacesContext.getCurrentInstance().addMessage(null, msg);
    }

    public String goToAdd() {
        return "add.xhtml?faces-redirect=true";
    }

    public void deleteTask(final TaskDTO task) {
        tasks.remove(task);
        taskService.delete(user.getId(), task);
        @NotNull final FacesMessage msg = new FacesMessage("Task Deleted", task.getName());
        FacesContext.getCurrentInstance().addMessage(null, msg);
    }

    public List<TaskDTO> getTasks() {
        return tasks;
    }

    public List<ProjectDTO> getProjects() {
        return projectService.getAll(user.getId());
    }
    public List<Status> getStatuses() { return Arrays.asList(Status.values()); }


    public void setName(String name) {
        task.setName(name);
    }

    public String getName() {
        return task.getName();
    }

    public void setDescription(String description) {
        task.setDescription(description);
    }

    public String getDescription() {
        return task.getDescription();
    }

    public void setStartDate(Date startDate) {
        task.setStartDate(startDate);
    }

    public Date getStartDate() {
        return task.getStartDate();
    }

    public void setEndDate(Date endDate) {
        task.setEndDate(endDate);
    }

    public Date getEndDate() {
        return task.getEndDate();
    }

    public void setProjectId(String projectId) {
        task.setProjectId(projectId);
    }

    public String getProjectId() {
        return task.getProjectId();
    }

    public void setStatus(Status status) {
        task.setStatus(status);
    }

    public Status getStatus() {
        return task.getStatus();
    }
}

src/main/webapp/WEB-INF/views/task/add.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui">
<h:head>
</h:head>
<h:body>
    <ui:include src="/WEB-INF/views/templates/menu.xhtml" >
        <ui:param name="active" value="2" />
    </ui:include>
    <h:form id="addTaskForm">
        <p:panel header="Add Task" style="width: 580px;">
            <p:messages/>
            <h:panelGrid columns="2" cellpadding="5">
                <p:outputLabel for="name" value="Name:"/>
                <p:inputText id="name" value="#{task.name}" label="Name"
                             placeholder="Name" />

                <p:outputLabel for="description" value="Description:"/>
                <p:inputText id="description" value="#{task.description}" label="Description"
                             placeholder="Description" />

                <p:outputLabel for="startDate" value="Start Date:"/>
                <p:calendar id="startDate" value="#{task.startDate}" pattern="MM/dd/yyyy HH:mm:ss"/>

                <p:outputLabel for="endDate" value="End Date:"/>
                <p:calendar id="endDate" value="#{task.endDate}" pattern="MM/dd/yyyy HH:mm:ss"/>

                <p:outputLabel for="projectName" value="Project Name:"/>
                <p:selectOneMenu id="projectName" value="#{task.projectId}" >
                    <f:selectItem itemLabel="--None--" itemValue="" />
                    <f:selectItems value="#{task.projects}" var="project"
                                   itemLabel="#{project.name}" itemValue="#{project.id}" />
                </p:selectOneMenu>

                <p:outputLabel value="Status:" />
                <p:selectOneRadio id="status" value="#{task.status}" unselectable="false">
                    <f:selectItems value="#{task.statuses}" var="status"
                                   itemLabel="#{status.name}" itemValue="#{status}" />
                </p:selectOneRadio>
                <p:outputLabel value="" />
                <p:commandButton value="Add" icon="fa fa-check" action="#{project.addProject()}" ajax="false"/>
            </h:panelGrid>
        </p:panel>
    </h:form>
</h:body>
</html>

src/main/webapp/WEB-INF/views/task/list.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui">

<h:head>
    <title>Task list page</title>
</h:head>

<h:body>
    <ui:include src="/WEB-INF/views/templates/menu.xhtml" >
        <ui:param name="active" value="2" />
    </ui:include>
    <h:form id="taskList">
        <p:growl id="msgs" showDetail="true"/>
        <p:dataTable id="dataTable" var="taskVar" editable="true" paginator="true" rows="20"  value="#{task.tasks}">
            <f:facet name="header">
                Tasks list
            </f:facet>

            <p:ajax event="rowEdit" listener="#{task.onRowEdit}" update=":taskList:msgs" />
            <p:ajax event="rowEditCancel" listener="#{task.onRowCancel}" update=":taskList:msgs" />

            <h:inputHidden id="id" value="taskVar.id"/>

            <p:column sortBy="#{taskVar.name}" headerText="Name">
                <p:cellEditor>
                    <f:facet name="output"><h:outputText value="#{taskVar.name}" /></f:facet>
                    <f:facet name="input"><p:inputText value="#{taskVar.name}" style="width:100%"/></f:facet>
                </p:cellEditor>
            </p:column>

            <p:column sortBy="#{taskVar.description}" headerText="Description">
                <p:cellEditor>
                    <f:facet name="output"><h:outputText value="#{taskVar.description}" /></f:facet>
                    <f:facet name="input"><p:inputText value="#{taskVar.description}" style="width:100%"/></f:facet>
                </p:cellEditor>
            </p:column>

            <p:column sortBy="#{taskVar.startDate}" headerText="Start Date">
                <p:cellEditor>
                    <f:facet name="output">
                        <h:outputText value="#{menu.dateFormat(taskVar.startDate)}" />
                    </f:facet>
                    <f:facet name="input">
                        <p:calendar value="#{taskVar.startDate}" pattern="MM/dd/yyyy HH:mm:ss"/>
                    </f:facet>
                </p:cellEditor>
            </p:column>

            <p:column sortBy="#{taskVar.endDate}" headerText="End Date">
                <p:cellEditor>
                    <f:facet name="output">
                        <h:outputText value="#{menu.dateFormat(taskVar.endDate)}" />
                    </f:facet>
                    <f:facet name="input">
                        <p:calendar value="#{taskVar.endDate}" pattern="MM/dd/yyyy HH:mm:ss"/>
                    </f:facet>
                </p:cellEditor>
            </p:column>

            <p:column sortBy="#{taskVar.createDate}" headerText="Create Date">
                <p:cellEditor>
                    <f:facet name="output">
                        <h:outputText value="#{menu.dateFormat(taskVar.createDate)}" />
                    </f:facet>
                    <f:facet name="input">
                        <p:calendar value="#{taskVar.createDate}" pattern="MM/dd/yyyy HH:mm:ss"/>
                    </f:facet>
                </p:cellEditor>
            </p:column>

            <p:column sortBy="#{taskVar.status}" headerText="Status">
                <p:cellEditor>
                    <f:facet name="output">
                        <h:outputText value="#{taskVar.status}" />
                    </f:facet>
                    <f:facet name="input">
                        <h:selectOneMenu value="#{taskVar.status}" style="width:100%">
                            <f:selectItems value="#{task.statuses}" var="status"
                                           itemLabel="#{status.name}" itemValue="#{status}" />
                        </h:selectOneMenu>
                    </f:facet>
                </p:cellEditor>
            </p:column>

            <p:column sortBy="#{taskVar.projectName}" headerText="Project Name">
                <p:cellEditor>
                    <f:facet name="output">
                        <h:outputText value="#{taskVar.projectName}" />
                    </f:facet>
                    <f:facet name="input">
                        <p:selectOneMenu value="#{taskVar.projectId}" style="width:100%">
                            <f:selectItem itemLabel="--None--" itemValue="" />
                            <f:selectItems value="#{task.projects}" var="project"
                                           itemLabel="#{project.name}" itemValue="#{project.id}" />
                        </p:selectOneMenu>
                    </f:facet>
                </p:cellEditor>
            </p:column>

            <p:column style="width:35px">
                <p:rowEditor />
            </p:column>

            <p:column headerText="Delete" style="text-align: center">
                <p:commandButton icon="fa fa-fw fa-remove" id="deleteTask" value="Delete" action="#{task.deleteTask(taskVar)}" update="taskList"/>
            </p:column>
        </p:dataTable>
    </h:form>
    <p:commandButton icon="fa fa-plus" value="Add" action="#{task.goToAdd}" />
</h:body>
</html>